include theos/makefiles/common.mk

internal-stage::
	$(ECHO_NOTHING)mkdir -p $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences$(ECHO_END)
	$(ECHO_NOTHING)cp AppNoti.plist $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/AppNoti.plist$(ECHO_END)
